In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np

In [4]:
# 1-d Array
arr1=np.array([1,2,3,4,5])

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
# 2-d Array
arr2=np.array([[1,2,3],[4,5,6]])

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(arr2.ndim)

2


In [11]:
# 0-d Array
arr=np.array(55)
arr

array(55)

In [13]:
print(arr.ndim)

0


In [14]:
arr3=np.zeros((3,5))

In [15]:
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
arr3=np.ones((3,6))
arr3

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
print(arr3.ndim)

2


In [9]:
arr2=np.array([[1,2,3],[4,5,6]])

In [11]:
# 2nd element on 1st row
print(arr2[0,2])

3


In [12]:
print(arr2[1,2])

6
