NumPy stands for Numerical Python.

NumPy is a Python library used for working with array.

It also has functions for working in domain of linear algebra, fourier transform, and matries.

NumPy aims to provide an array object that is up to 50x faster than traditional Python ists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np

In [4]:
# 1-d Array
arr1=np.array([1,2,3,4,5])

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
# 2-d Array
arr2=np.array([[1,2,3],[4,5,6]])

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(arr2.ndim)

2


In [11]:
# 0-d Array
arr=np.array(55)
arr

array(55)

In [13]:
print(arr.ndim)

0


In [14]:
arr3=np.zeros((3,5))

In [15]:
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
arr3=np.ones((3,6))
arr3

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
print(arr3.ndim)

2


In [9]:
arr2=np.array([[1,2,3],[4,5,6]])

In [11]:
# 2nd element on 1st row
print(arr2[0,2])

3


In [12]:
print(arr2[1,2])

6


In [1]:
import numpy as np

In [2]:
arr3 = np.array([1,2,3,4,5,6,7])
print(arr3[1:5])

[2 3 4 5]


In [4]:
arr4 = np.array([1,2,3,4,5,6,7])
print(arr4[4:])

[5 6 7]


In [5]:
arr5 = np.array([1,2,3,4,5,6,7])
print(arr5[:4])

[1 2 3 4]


In [6]:
arr6 = np.array([1,2,3,4,5,6,7])
print(arr6[-3:-1])

[5 6]


In [7]:
# Return every other element from index 1 to 5:
arr7 = np.array([1,2,3,4,5,6,7])
print(arr7[1:5:2])

[2 4]


In [8]:
# Shape of an Array Shape that returns a tuple with each index having the 
#number of corresponding elements.
arr8 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr8.shape)

(2, 4)


In [9]:
# Reshape from 1D to 2D 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
# Reshape From 1D to 3D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [11]:
# Iterating Array
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [12]:
# Iterate on the elements of the following 2D array
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [14]:
# Numpy Joining Array
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [15]:
# Join two 2D array along rows, axis=1
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1, arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [16]:
# Splitting Numpy Array
# Spliting is reverse operation of Joining
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [17]:
# Splitting Numpy Array
# Spliting is reverse operation of Joining
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [23]:
# Random Numbers
# Numpy offers the random module to work with random numbers.
# Generate a random integer from 0 to 100.
from numpy import random
x = random.randint(100)
print(x)

51


In [24]:
# Random models rand() method returns a random float between 0 and 1.
from numpy import random
x = random.rand()
print(x)

0.3126168096648333


In [25]:
# Generate Random Array
from numpy import random
x = random.randint(100, size = (5))
print(x)

[ 1 33 30 70 62]


In [26]:
# A 2D array with 3 rows, each row containing 5 random integers from 0 to 100.
from numpy import random 
x = random.randint(100, size=(3,5))
print(x)

[[ 9 60 69 19 34]
 [82 76 90 64 83]
 [56 82 65 58 66]]


In [28]:
# Generate a 1D array containing 5 random floats.
from numpy import random
x = random.rand(5)
print(x)

[0.13375787 0.79992752 0.56241679 0.35230372 0.38545271]


In [29]:
# Generate a 2D array with 3 rows, each row containing 5 random numbers.
from numpy import random
x = random.rand(3,5)
print(x)

[[0.12760132 0.64454938 0.97432835 0.56978968 0.76630725]
 [0.13561458 0.24255525 0.81636048 0.67806334 0.68766055]
 [0.90761233 0.7060878  0.79791355 0.36654359 0.81609828]]
